[STM] Add USB3 support on STxH407
Added support for the XHCI controller present on the STxH407.
This initial support for the USB3.0 controller is host mode only. I
have tested the mass storage profile for this controller on the B2120
board.

Support for only the USB3.0 port has beed added for STxH407. On this
USB3.0 port i have tested both USB2.0 and USB3.0 mass storage devices.

Addition of XHCI/USB3.0 introduced following compilation error:

armv7-linux-ld.bfd: error: /opt/STM/STLinux-2.4/devkit/armv7/lib/gcc/arm-cortex-linux-gnueabi/4.7.3/libgcc.a(bpabi.o) uses VFP register arguments, u-boot does not
armv7-linux-ld.bfd: failed to merge target specific data of file /opt/STM/STLinux-2.4/devkit/armv7/lib/gcc/arm-cortex-linux-gnueabi/4.7.3/libgcc.a(bpabi.o)
armv7-linux-ld.bfd: error: /opt/STM/STLinux-2.4/devkit/armv7/lib/gcc/arm-cortex-linux-gnueabi/4.7.3/libgcc.a(_divdi3.o) uses VFP register arguments, u-boot does not
armv7-linux-ld.bfd: failed to merge target specific data of file /opt/STM/STLinux-2.4/devkit/armv7/lib/gcc/arm-cortex-linux-gnueabi/4.7.3/libgcc.a(_divdi3.o)
armv7-linux-ld.bfd: error: /opt/STM/STLinux-2.4/devkit/armv7/lib/gcc/arm-cortex-linux-gnueabi/4.7.3/libgcc.a(_udivdi3.o) uses VFP register arguments, u-boot does not
armv7-linux-ld.bfd: failed to merge target specific data of file /opt/STM/STLinux-2.4/devkit/armv7/lib/gcc/arm-cortex-linux-gnueabi/4.7.3/libgcc.a(_udivdi3.o)
make: *** [u-boot] Error 1

This error is due to the incompatiblity in the floating point usage.
To solve this error, i have changed the PLATFORM_RELFLAGS for ARM
to  "-mfloat-abi=hard -mfpu=vfpv3" from "-msoft-float"

USB3.0 support has been tested only on a single B2120 board
with STxH407 1.x SOC

Signed-off-by: Sachin Verma <sachin.verma@st.com>